version: "3"
services:
  shapass:
    image: hoshoyo/shapass
    ports:
      - "8000:8000"
    env_file:
      - .devenv
    networks:
      - shapass-net-dev
    volumes:
      - .:/api
    command: ["go", "run", "./src/apiv2.go", "./src/main.go", "./src/middleware.go", "./src/utils.go"]
  postgres:
    image: hoshoyo/shapass-db
    ports:
      - "5555:5432"
    networks:
      - shapass-net-dev
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
networks:
  shapass-net-dev: